---
global:
  scrape_interval: "60s"
  evaluation_interval: "60s"

scrape_configs:
  - job_name: dev-push-gateway
    metrics_path: /metrics
    scheme: http
    honor_labels: true
    static_configs:
    - targets: ['prom-pushgateway:9091']
      labels:
        service: 'prom-pushgateway'

  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
