name: PR Deployment Testing
on:
  pull_request:
    types: [ labeled ]

jobs:
  pr_testing:
    if: ${{ github.event.label.name == 'pr-deployment' }}
    runs-on: ubuntu-latest
    needs: deployment_ready
    steps:
    - uses: actions/checkout@v2
    - name: Trigger tests on PR deployment
      run: bash ./.github/workflows/scripts/pr_deployment_test.sh invoke_pr_test 81148901 ${{ secrets.TESTING_TRIGGER_PAT }} ${{ github.event.number }}
      shell: bash

  deployment_ready:
    if: ${{ github.event.label.name == 'pr-deployment' }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Wait for PR deployment completion
        run: bash ./.github/workflows/scripts/pr_deployment_test.sh wait_for_pr_deployment ${{ github.event.number }}
        shell: bash
